import { type Module, inject } from 'langium';
import {
  createDefaultModule,
  createDefaultSharedModule,
  type DefaultSharedModuleContext,
  type LangiumServices,
  type LangiumSharedServices,
  type PartialLangiumServices,
} from 'langium/lsp';
import {
  BpmnScriptGeneratedModule,
  BpmnScriptGeneratedSharedModule,
} from './generated/module.js';
import {
  BpmnScriptValidator,
  registerValidationChecks,
} from './bpmn-script-validator.js';
import {
  DefaultVariableSymbolProvider,
  type VariableSymbolProvider,
} from './variable-symbol-provider.js';

/**
 * Declaration of custom services - add your own service classes here.
 *
 * The {@link VariableSymbolProvider} lives in the `references` group (it resolves
 * variable identifiers, the references layer's concern).
 */
export type BpmnScriptAddedServices = {
  references: {
    VariableSymbolProvider: VariableSymbolProvider;
  };
  validation: {
    BpmnScriptValidator: BpmnScriptValidator;
  };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type BpmnScriptServices = LangiumServices & BpmnScriptAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 *
 * selected services, while the custom services must be fully specified.
 */
export const BpmnScriptModule: Module<
  BpmnScriptServices,
  PartialLangiumServices & BpmnScriptAddedServices
> = {
  references: {
    VariableSymbolProvider: () => new DefaultVariableSymbolProvider(),
  },
  validation: {
    BpmnScriptValidator: (services) => new BpmnScriptValidator(services),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createBpmnScriptServices(context: DefaultSharedModuleContext): {
  shared: LangiumSharedServices;
  BpmnScript: BpmnScriptServices;
} {
  const shared = inject(
    createDefaultSharedModule(context),
    BpmnScriptGeneratedSharedModule,
  );
  const BpmnScript = inject(
    createDefaultModule({ shared }),
    BpmnScriptGeneratedModule,
    BpmnScriptModule,
  );
  shared.ServiceRegistry.register(BpmnScript);
  registerValidationChecks(BpmnScript);
  if (!context.connection) {
    // We don't run inside a language server
    // Therefore, initialize the configuration provider instantly
    shared.workspace.ConfigurationProvider.initialized({});
  }
  return { shared, BpmnScript };
}
